services:
  - type: web
    name: mediinsight-backend
    env: docker
    plan: free
    region: ohio
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: mediinsight-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: mediinsight-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: mediinsight-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: mediinsight-db
          property: password
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: mediinsight-db
    databaseName: mediinsight
    user: renderuser
    plan: free
    region: ohio
